version: "3.8"

services:
  frontend:
    container_name: vue-app
    build:
      context: .
      dockerfile: ./deployments/frontend/Dockerfile
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - front-network

  backend:
    container_name: express-app
    build:
      context: .
      dockerfile: ./deployments/backend/Dockerfile
    volumes:
      - "./backend:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - front-network
      - back-network

  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tmdb
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - back-network

volumes:
  db:
    driver: local

networks:
  front-network:
  back-network:
