version: "3.8"

services:
  frontend:
    container_name: vue-app
    build:
      context: .
      dockerfile: ./deployments/frontend/Dockerfile
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - "5173:5173"

  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tmdb
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
