# POST http://localhost:3000/api/signup
# Content-Type: application/json

# {
#   "username": "hadari",
#   "password": "hadari",
#   "email": "hadari"
# }

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "abdlali",
  "password": "abdlali"
}


###

GET http://localhost:3000/api/username
Cookie: access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY3JlYXRlZEF0IjoiMjAyMy0wMi0yNlQyMDozNzo0OC4wODBaIiwidXBkYXRlZEF0IjoiMjAyMy0wMi0yNlQyMDozNzo0OC4wODBaIiwidXNlcm5hbWUiOiJ5YXNzaW5lIiwicGFzc3dvcmQiOiIkMmIkMTAkL2RRZlpCRTNHd3dvZ0J0WU9OckdEdWh0am0xc2JQMk1XMTYuY0tHRFF5UEFNQzh4Wm4xZkMiLCJlbWFpbCI6Inlhc3NpbmUiLCJpYXQiOjE2Nzc0NDYwMzR9.jAbbIVEFa3oEuj-SS7VEndw9
